name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.8
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  meta: ^1.16.0 
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.17
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass: FlutterPaystackPlugin
      ios:
        pluginClass: FlutterPaystackPlugin

  assets:
    - assets/images/

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.0.0"